/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Account {
  export type InfoStruct = { owner: string; number: BigNumberish };

  export type InfoStructOutput = [string, BigNumber] & {
    owner: string;
    number: BigNumber;
  };
}

export declare namespace Types {
  export type ParStruct = { sign: boolean; value: BigNumberish };

  export type ParStructOutput = [boolean, BigNumber] & {
    sign: boolean;
    value: BigNumber;
  };

  export type WeiStruct = { sign: boolean; value: BigNumberish };

  export type WeiStructOutput = [boolean, BigNumber] & {
    sign: boolean;
    value: BigNumber;
  };

  export type TotalParStruct = { borrow: BigNumberish; supply: BigNumberish };

  export type TotalParStructOutput = [BigNumber, BigNumber] & {
    borrow: BigNumber;
    supply: BigNumber;
  };

  export type AssetAmountStruct = {
    sign: boolean;
    denomination: BigNumberish;
    ref: BigNumberish;
    value: BigNumberish;
  };

  export type AssetAmountStructOutput = [boolean, number, number, BigNumber] & {
    sign: boolean;
    denomination: number;
    ref: number;
    value: BigNumber;
  };
}

export declare namespace Monetary {
  export type ValueStruct = { value: BigNumberish };

  export type ValueStructOutput = [BigNumber] & { value: BigNumber };

  export type PriceStruct = { value: BigNumberish };

  export type PriceStructOutput = [BigNumber] & { value: BigNumber };
}

export declare namespace Decimal {
  export type D256Struct = { value: BigNumberish };

  export type D256StructOutput = [BigNumber] & { value: BigNumber };
}

export declare namespace Interest {
  export type IndexStruct = {
    borrow: BigNumberish;
    supply: BigNumberish;
    lastUpdate: BigNumberish;
  };

  export type IndexStructOutput = [BigNumber, BigNumber, number] & {
    borrow: BigNumber;
    supply: BigNumber;
    lastUpdate: number;
  };

  export type RateStruct = { value: BigNumberish };

  export type RateStructOutput = [BigNumber] & { value: BigNumber };
}

export declare namespace Storage {
  export type MarketStruct = {
    token: string;
    totalPar: Types.TotalParStruct;
    index: Interest.IndexStruct;
    priceOracle: string;
    interestSetter: string;
    marginPremium: Decimal.D256Struct;
    spreadPremium: Decimal.D256Struct;
    isClosing: boolean;
  };

  export type MarketStructOutput = [
    string,
    Types.TotalParStructOutput,
    Interest.IndexStructOutput,
    string,
    string,
    Decimal.D256StructOutput,
    Decimal.D256StructOutput,
    boolean
  ] & {
    token: string;
    totalPar: Types.TotalParStructOutput;
    index: Interest.IndexStructOutput;
    priceOracle: string;
    interestSetter: string;
    marginPremium: Decimal.D256StructOutput;
    spreadPremium: Decimal.D256StructOutput;
    isClosing: boolean;
  };

  export type RiskLimitsStruct = {
    marginRatioMax: BigNumberish;
    liquidationSpreadMax: BigNumberish;
    earningsRateMax: BigNumberish;
    marginPremiumMax: BigNumberish;
    spreadPremiumMax: BigNumberish;
    minBorrowedValueMax: BigNumberish;
  };

  export type RiskLimitsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    marginRatioMax: BigNumber;
    liquidationSpreadMax: BigNumber;
    earningsRateMax: BigNumber;
    marginPremiumMax: BigNumber;
    spreadPremiumMax: BigNumber;
    minBorrowedValueMax: BigNumber;
  };

  export type RiskParamsStruct = {
    marginRatio: Decimal.D256Struct;
    liquidationSpread: Decimal.D256Struct;
    earningsRate: Decimal.D256Struct;
    minBorrowedValue: Monetary.ValueStruct;
  };

  export type RiskParamsStructOutput = [
    Decimal.D256StructOutput,
    Decimal.D256StructOutput,
    Decimal.D256StructOutput,
    Monetary.ValueStructOutput
  ] & {
    marginRatio: Decimal.D256StructOutput;
    liquidationSpread: Decimal.D256StructOutput;
    earningsRate: Decimal.D256StructOutput;
    minBorrowedValue: Monetary.ValueStructOutput;
  };
}

export declare namespace Actions {
  export type ActionArgsStruct = {
    actionType: BigNumberish;
    accountId: BigNumberish;
    amount: Types.AssetAmountStruct;
    primaryMarketId: BigNumberish;
    secondaryMarketId: BigNumberish;
    otherAddress: string;
    otherAccountId: BigNumberish;
    data: BytesLike;
  };

  export type ActionArgsStructOutput = [
    number,
    BigNumber,
    Types.AssetAmountStructOutput,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string
  ] & {
    actionType: number;
    accountId: BigNumber;
    amount: Types.AssetAmountStructOutput;
    primaryMarketId: BigNumber;
    secondaryMarketId: BigNumber;
    otherAddress: string;
    otherAccountId: BigNumber;
    data: string;
  };
}

export declare namespace ISoloMargin {
  export type OperatorArgStruct = { operator: string; trusted: boolean };

  export type OperatorArgStructOutput = [string, boolean] & {
    operator: string;
    trusted: boolean;
  };
}

export interface ISoloMarginInterface extends utils.Interface {
  contractName: "ISoloMargin";
  functions: {
    "getAccountBalances((address,uint256))": FunctionFragment;
    "getAccountPar((address,uint256),uint256)": FunctionFragment;
    "getAccountStatus((address,uint256))": FunctionFragment;
    "getAccountValues((address,uint256))": FunctionFragment;
    "getAccountWei((address,uint256),uint256)": FunctionFragment;
    "getAdjustedAccountValues((address,uint256))": FunctionFragment;
    "getEarningsRate()": FunctionFragment;
    "getIsGlobalOperator(address)": FunctionFragment;
    "getIsLocalOperator(address,address)": FunctionFragment;
    "getLiquidationSpread()": FunctionFragment;
    "getLiquidationSpreadForPair(uint256,uint256)": FunctionFragment;
    "getMarginRatio()": FunctionFragment;
    "getMarket(uint256)": FunctionFragment;
    "getMarketCachedIndex(uint256)": FunctionFragment;
    "getMarketCurrentIndex(uint256)": FunctionFragment;
    "getMarketInterestRate(uint256)": FunctionFragment;
    "getMarketInterestSetter(uint256)": FunctionFragment;
    "getMarketIsClosing(uint256)": FunctionFragment;
    "getMarketMarginPremium(uint256)": FunctionFragment;
    "getMarketPrice(uint256)": FunctionFragment;
    "getMarketPriceOracle(uint256)": FunctionFragment;
    "getMarketSpreadPremium(uint256)": FunctionFragment;
    "getMarketTokenAddress(uint256)": FunctionFragment;
    "getMarketTotalPar(uint256)": FunctionFragment;
    "getMarketWithInfo(uint256)": FunctionFragment;
    "getMinBorrowedValue()": FunctionFragment;
    "getNumExcessTokens(uint256)": FunctionFragment;
    "getNumMarkets()": FunctionFragment;
    "getRiskLimits()": FunctionFragment;
    "getRiskParams()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "operate((address,uint256)[],(uint8,uint256,(bool,uint8,uint8,uint256),uint256,uint256,address,uint256,bytes)[])": FunctionFragment;
    "owner()": FunctionFragment;
    "ownerAddMarket(address,address,address,(uint256),(uint256))": FunctionFragment;
    "ownerSetEarningsRate((uint256))": FunctionFragment;
    "ownerSetGlobalOperator(address,bool)": FunctionFragment;
    "ownerSetInterestSetter(uint256,address)": FunctionFragment;
    "ownerSetIsClosing(uint256,bool)": FunctionFragment;
    "ownerSetLiquidationSpread((uint256))": FunctionFragment;
    "ownerSetMarginPremium(uint256,(uint256))": FunctionFragment;
    "ownerSetMarginRatio((uint256))": FunctionFragment;
    "ownerSetMinBorrowedValue((uint256))": FunctionFragment;
    "ownerSetPriceOracle(uint256,address)": FunctionFragment;
    "ownerSetSpreadPremium(uint256,(uint256))": FunctionFragment;
    "ownerWithdrawExcessTokens(uint256,address)": FunctionFragment;
    "ownerWithdrawUnsupportedTokens(address,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setOperators((address,bool)[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAccountBalances",
    values: [Account.InfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountPar",
    values: [Account.InfoStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountStatus",
    values: [Account.InfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountValues",
    values: [Account.InfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountWei",
    values: [Account.InfoStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdjustedAccountValues",
    values: [Account.InfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getEarningsRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIsGlobalOperator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIsLocalOperator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidationSpread",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidationSpreadForPair",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarginRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCachedIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCurrentIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInterestRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInterestSetter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketIsClosing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketMarginPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketPriceOracle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketSpreadPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketTokenAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketTotalPar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketWithInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinBorrowedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumExcessTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskLimits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskParams",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operate",
    values: [Account.InfoStruct[], Actions.ActionArgsStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerAddMarket",
    values: [string, string, string, Decimal.D256Struct, Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetEarningsRate",
    values: [Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetGlobalOperator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetInterestSetter",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetIsClosing",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetLiquidationSpread",
    values: [Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetMarginPremium",
    values: [BigNumberish, Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetMarginRatio",
    values: [Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetMinBorrowedValue",
    values: [Monetary.ValueStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPriceOracle",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetSpreadPremium",
    values: [BigNumberish, Decimal.D256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerWithdrawExcessTokens",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerWithdrawUnsupportedTokens",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperators",
    values: [ISoloMargin.OperatorArgStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAccountBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountPar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdjustedAccountValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEarningsRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsGlobalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsLocalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidationSpread",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidationSpreadForPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarginRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCachedIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCurrentIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInterestSetter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketIsClosing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketMarginPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketSpreadPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketTotalPar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketWithInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinBorrowedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumExcessTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerAddMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetEarningsRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetGlobalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetInterestSetter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetIsClosing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetLiquidationSpread",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetMarginPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetMarginRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetMinBorrowedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetSpreadPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerWithdrawExcessTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerWithdrawUnsupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISoloMargin extends BaseContract {
  contractName: "ISoloMargin";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISoloMarginInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAccountBalances(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[string[], Types.ParStructOutput[], Types.WeiStructOutput[]]>;

    getAccountPar(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Types.ParStructOutput]>;

    getAccountStatus(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

    getAccountWei(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Types.WeiStructOutput]>;

    getAdjustedAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

    getEarningsRate(
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getIsLocalOperator(
      _owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getLiquidationSpread(
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getLiquidationSpreadForPair(
      heldMarketId: BigNumberish,
      owedMarketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getMarginRatio(
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getMarket(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Storage.MarketStructOutput]>;

    getMarketCachedIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Interest.IndexStructOutput]>;

    getMarketCurrentIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Interest.IndexStructOutput]>;

    getMarketInterestRate(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Interest.RateStructOutput]>;

    getMarketInterestSetter(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMarketIsClosing(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getMarketMarginPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getMarketPrice(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMarketPriceOracle(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMarketSpreadPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Decimal.D256StructOutput]>;

    getMarketTokenAddress(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMarketTotalPar(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Types.TotalParStructOutput]>;

    getMarketWithInfo(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        Storage.MarketStructOutput,
        Interest.IndexStructOutput,
        Monetary.PriceStructOutput,
        Interest.RateStructOutput
      ]
    >;

    getMinBorrowedValue(
      overrides?: CallOverrides
    ): Promise<[Monetary.ValueStructOutput]>;

    getNumExcessTokens(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Types.WeiStructOutput]>;

    getNumMarkets(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRiskLimits(
      overrides?: CallOverrides
    ): Promise<[Storage.RiskLimitsStructOutput]>;

    getRiskParams(
      overrides?: CallOverrides
    ): Promise<[Storage.RiskParamsStructOutput]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    operate(
      accounts: Account.InfoStruct[],
      actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    ownerAddMarket(
      token: string,
      priceOracle: string,
      interestSetter: string,
      marginPremium: Decimal.D256Struct,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetEarningsRate(
      earningsRate: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetInterestSetter(
      marketId: BigNumberish,
      interestSetter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetIsClosing(
      marketId: BigNumberish,
      isClosing: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetLiquidationSpread(
      spread: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetMarginPremium(
      marketId: BigNumberish,
      marginPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetMarginRatio(
      ratio: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetMinBorrowedValue(
      minBorrowedValue: Monetary.ValueStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetPriceOracle(
      marketId: BigNumberish,
      priceOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerSetSpreadPremium(
      marketId: BigNumberish,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerWithdrawExcessTokens(
      marketId: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerWithdrawUnsupportedTokens(
      token: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOperators(
      args: ISoloMargin.OperatorArgStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAccountBalances(
    account: Account.InfoStruct,
    overrides?: CallOverrides
  ): Promise<[string[], Types.ParStructOutput[], Types.WeiStructOutput[]]>;

  getAccountPar(
    account: Account.InfoStruct,
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Types.ParStructOutput>;

  getAccountStatus(
    account: Account.InfoStruct,
    overrides?: CallOverrides
  ): Promise<number>;

  getAccountValues(
    account: Account.InfoStruct,
    overrides?: CallOverrides
  ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

  getAccountWei(
    account: Account.InfoStruct,
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Types.WeiStructOutput>;

  getAdjustedAccountValues(
    account: Account.InfoStruct,
    overrides?: CallOverrides
  ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

  getEarningsRate(overrides?: CallOverrides): Promise<Decimal.D256StructOutput>;

  getIsGlobalOperator(
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getIsLocalOperator(
    _owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getLiquidationSpread(
    overrides?: CallOverrides
  ): Promise<Decimal.D256StructOutput>;

  getLiquidationSpreadForPair(
    heldMarketId: BigNumberish,
    owedMarketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Decimal.D256StructOutput>;

  getMarginRatio(overrides?: CallOverrides): Promise<Decimal.D256StructOutput>;

  getMarket(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Storage.MarketStructOutput>;

  getMarketCachedIndex(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Interest.IndexStructOutput>;

  getMarketCurrentIndex(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Interest.IndexStructOutput>;

  getMarketInterestRate(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Interest.RateStructOutput>;

  getMarketInterestSetter(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMarketIsClosing(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getMarketMarginPremium(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Decimal.D256StructOutput>;

  getMarketPrice(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMarketPriceOracle(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMarketSpreadPremium(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Decimal.D256StructOutput>;

  getMarketTokenAddress(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMarketTotalPar(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Types.TotalParStructOutput>;

  getMarketWithInfo(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      Storage.MarketStructOutput,
      Interest.IndexStructOutput,
      Monetary.PriceStructOutput,
      Interest.RateStructOutput
    ]
  >;

  getMinBorrowedValue(
    overrides?: CallOverrides
  ): Promise<Monetary.ValueStructOutput>;

  getNumExcessTokens(
    marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Types.WeiStructOutput>;

  getNumMarkets(overrides?: CallOverrides): Promise<BigNumber>;

  getRiskLimits(
    overrides?: CallOverrides
  ): Promise<Storage.RiskLimitsStructOutput>;

  getRiskParams(
    overrides?: CallOverrides
  ): Promise<Storage.RiskParamsStructOutput>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  operate(
    accounts: Account.InfoStruct[],
    actions: Actions.ActionArgsStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  ownerAddMarket(
    token: string,
    priceOracle: string,
    interestSetter: string,
    marginPremium: Decimal.D256Struct,
    spreadPremium: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetEarningsRate(
    earningsRate: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetGlobalOperator(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetInterestSetter(
    marketId: BigNumberish,
    interestSetter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetIsClosing(
    marketId: BigNumberish,
    isClosing: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetLiquidationSpread(
    spread: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetMarginPremium(
    marketId: BigNumberish,
    marginPremium: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetMarginRatio(
    ratio: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetMinBorrowedValue(
    minBorrowedValue: Monetary.ValueStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetPriceOracle(
    marketId: BigNumberish,
    priceOracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerSetSpreadPremium(
    marketId: BigNumberish,
    spreadPremium: Decimal.D256Struct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerWithdrawExcessTokens(
    marketId: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerWithdrawUnsupportedTokens(
    token: string,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOperators(
    args: ISoloMargin.OperatorArgStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAccountBalances(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[string[], Types.ParStructOutput[], Types.WeiStructOutput[]]>;

    getAccountPar(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Types.ParStructOutput>;

    getAccountStatus(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<number>;

    getAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

    getAccountWei(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Types.WeiStructOutput>;

    getAdjustedAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<[Monetary.ValueStructOutput, Monetary.ValueStructOutput]>;

    getEarningsRate(
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getIsLocalOperator(
      _owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getLiquidationSpread(
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getLiquidationSpreadForPair(
      heldMarketId: BigNumberish,
      owedMarketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getMarginRatio(
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getMarket(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Storage.MarketStructOutput>;

    getMarketCachedIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Interest.IndexStructOutput>;

    getMarketCurrentIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Interest.IndexStructOutput>;

    getMarketInterestRate(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Interest.RateStructOutput>;

    getMarketInterestSetter(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMarketIsClosing(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getMarketMarginPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getMarketPrice(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMarketPriceOracle(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMarketSpreadPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Decimal.D256StructOutput>;

    getMarketTokenAddress(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMarketTotalPar(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Types.TotalParStructOutput>;

    getMarketWithInfo(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        Storage.MarketStructOutput,
        Interest.IndexStructOutput,
        Monetary.PriceStructOutput,
        Interest.RateStructOutput
      ]
    >;

    getMinBorrowedValue(
      overrides?: CallOverrides
    ): Promise<Monetary.ValueStructOutput>;

    getNumExcessTokens(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Types.WeiStructOutput>;

    getNumMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    getRiskLimits(
      overrides?: CallOverrides
    ): Promise<Storage.RiskLimitsStructOutput>;

    getRiskParams(
      overrides?: CallOverrides
    ): Promise<Storage.RiskParamsStructOutput>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    operate(
      accounts: Account.InfoStruct[],
      actions: Actions.ActionArgsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    ownerAddMarket(
      token: string,
      priceOracle: string,
      interestSetter: string,
      marginPremium: Decimal.D256Struct,
      spreadPremium: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetEarningsRate(
      earningsRate: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetInterestSetter(
      marketId: BigNumberish,
      interestSetter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetIsClosing(
      marketId: BigNumberish,
      isClosing: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetLiquidationSpread(
      spread: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetMarginPremium(
      marketId: BigNumberish,
      marginPremium: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetMarginRatio(
      ratio: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetMinBorrowedValue(
      minBorrowedValue: Monetary.ValueStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPriceOracle(
      marketId: BigNumberish,
      priceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetSpreadPremium(
      marketId: BigNumberish,
      spreadPremium: Decimal.D256Struct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerWithdrawExcessTokens(
      marketId: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerWithdrawUnsupportedTokens(
      token: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setOperators(
      args: ISoloMargin.OperatorArgStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAccountBalances(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountPar(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountStatus(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountWei(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdjustedAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEarningsRate(overrides?: CallOverrides): Promise<BigNumber>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIsLocalOperator(
      _owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidationSpread(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidationSpreadForPair(
      heldMarketId: BigNumberish,
      owedMarketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarginRatio(overrides?: CallOverrides): Promise<BigNumber>;

    getMarket(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketCachedIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketCurrentIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketInterestRate(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketInterestSetter(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketIsClosing(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketMarginPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketPrice(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketPriceOracle(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketSpreadPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketTokenAddress(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketTotalPar(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketWithInfo(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBorrowedValue(overrides?: CallOverrides): Promise<BigNumber>;

    getNumExcessTokens(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    getRiskLimits(overrides?: CallOverrides): Promise<BigNumber>;

    getRiskParams(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    operate(
      accounts: Account.InfoStruct[],
      actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    ownerAddMarket(
      token: string,
      priceOracle: string,
      interestSetter: string,
      marginPremium: Decimal.D256Struct,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetEarningsRate(
      earningsRate: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetInterestSetter(
      marketId: BigNumberish,
      interestSetter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetIsClosing(
      marketId: BigNumberish,
      isClosing: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetLiquidationSpread(
      spread: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetMarginPremium(
      marketId: BigNumberish,
      marginPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetMarginRatio(
      ratio: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetMinBorrowedValue(
      minBorrowedValue: Monetary.ValueStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetPriceOracle(
      marketId: BigNumberish,
      priceOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerSetSpreadPremium(
      marketId: BigNumberish,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerWithdrawExcessTokens(
      marketId: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerWithdrawUnsupportedTokens(
      token: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOperators(
      args: ISoloMargin.OperatorArgStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAccountBalances(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountPar(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountStatus(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountWei(
      account: Account.InfoStruct,
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdjustedAccountValues(
      account: Account.InfoStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEarningsRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsLocalOperator(
      _owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidationSpread(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidationSpreadForPair(
      heldMarketId: BigNumberish,
      owedMarketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarginRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMarket(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketCachedIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketCurrentIndex(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketInterestRate(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketInterestSetter(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketIsClosing(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketMarginPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketPrice(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketPriceOracle(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketSpreadPremium(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketTokenAddress(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketTotalPar(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketWithInfo(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinBorrowedValue(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumExcessTokens(
      marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumMarkets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRiskLimits(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRiskParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    operate(
      accounts: Account.InfoStruct[],
      actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerAddMarket(
      token: string,
      priceOracle: string,
      interestSetter: string,
      marginPremium: Decimal.D256Struct,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetEarningsRate(
      earningsRate: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetInterestSetter(
      marketId: BigNumberish,
      interestSetter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetIsClosing(
      marketId: BigNumberish,
      isClosing: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetLiquidationSpread(
      spread: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetMarginPremium(
      marketId: BigNumberish,
      marginPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetMarginRatio(
      ratio: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetMinBorrowedValue(
      minBorrowedValue: Monetary.ValueStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetPriceOracle(
      marketId: BigNumberish,
      priceOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerSetSpreadPremium(
      marketId: BigNumberish,
      spreadPremium: Decimal.D256Struct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerWithdrawExcessTokens(
      marketId: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerWithdrawUnsupportedTokens(
      token: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOperators(
      args: ISoloMargin.OperatorArgStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
